/**
 * @file
 *
 * @author      Alexander Epstine
 * @mail        a@epstine.com
 * @brief
 *
 **************************************************************************************
 * Copyright (c) 2021, Alexander Epstine (a@epstine.com)
 **************************************************************************************
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#pragma once

namespace cs
{
	enum class ObjectDetectorKind {
		OBJECT_DETECTOR_NONE = 0,
		OBJECT_DETECTOR_TENSORFLOW_YOLOv5 = 1,
		OBJECT_DETECTOR_TENSORRT_YOLOv5 = 2,
		OBJECT_DETECTOR_OPENCV_YOLOv5 = 3,
		OBJECT_DETECTOR_OPENCV_YOLOv8 = 4,
		OBJECT_DETECTOR_TENSORRT_YOLOv8 = 5,
		AUDIO_RECOGNIZER_TFLITE = 6
	};

	enum class ObjectDetectorEvent {
		OBJECT_DETECTOR_EVENT_NONE = 0,
		OBJECT_DETECTOR_EVENT_DETECTED = 1,
		OBJECT_DETECTOR_EVENT_NOTDETECTED = 2,
		OBJECT_DETECTOR_EVENT_MOVED = 3
	};

	enum class VIDEO_STREAM_MODE
	{
		VIDEO_STREAM_MODE_NONE = 0,
		VIDEO_STREAM_MODE_SOURCE = 1,
		VIDEO_STREAM_MODE_DETECTOR = 2
	};

	enum class VIDEO_STREAM_ENGINE
	{
		VIDEO_STREAM_ENGINE_NONE = 0,
		VIDEO_STREAM_ENGINE_HTTP_MJPG = 1,
		VIDEO_STREAM_ENGINE_SIMPLE_GSTREAMER = 2
	};

	enum class INPUT_OUTPUT_DEVICE_KIND
	{
		INPUT_OUTPUT_DEVICE_KIND_NONE= 0,
		INPUT_OUTPUT_DEVICE_KIND_CAMERA = 1,
		INPUT_OUTPUT_DEVICE_KIND_MICROPHONE = 2,
		INPUT_OUTPUT_DEVICE_KIND_SPEAKER = 3,
		INPUT_OUTPUT_DEVICE_KIND_EARPHONES = 4,
		INPUT_OUTPUT_DEVICE_KIND_SENSOR = 5,
		INPUT_OUTPUT_DEVICE_KIND_VIDEO_STREAMER = 6
	};

#ifdef __WITH_SCRIPT_LANG__
	enum class SCRIPT_EXECUTE_MODE
	{
		SCRIPT_EXECUTE_MODE_NONE = 0,
		SCRIPT_EXECUTE_MODE_SYNC = 1,
		SCRIPT_EXECUTE_MODE_ASYNC = 2
	};
#endif
}
