/**
 * @file
 *
 * @author      Alexander Epstine
 * @mail        a@epstine.com
 * @brief
 *
 **************************************************************************************
 * Copyright (c) 2021, Alexander Epstine (a@epstine.com)
 **************************************************************************************
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#pragma once

namespace cs
{
	enum class ObjectDetectorKind {
		OBJECT_DETECTOR_NONE = 0,
		OBJECT_DETECTOR_TENSORFLOW_YOLOv5 = 1,
		OBJECT_DETECTOR_TENSORRT_YOLO = 2,
		OBJECT_DETECTOR_OPENCV_YOLOv5 = 3,
		OBJECT_DETECTOR_OPENCV_YOLOv8 = 4,
		AUDIO_RECOGNIZER_TFLITE = 6,
		HAAR_CASCADE_CLASSIFIER = 7,
		OBJECT_DETECTOR_SVC_GEMMA3 = 10,
		OBJECT_DETECTOR_GEMMA3 = 11,
		OBJECT_DETECTOR_SVC_QWEN = 12,
		OBJECT_DETECTOR_QWEN = 13
		//OBJECT_DETECTOR_TENSORRT_YOLOv12 = 14
	};

	enum class ObjectDetectorEvent {
		OBJECT_DETECTOR_EVENT_NONE = 0,
		OBJECT_DETECTOR_EVENT_DETECTED = 1,
		OBJECT_DETECTOR_EVENT_NOTDETECTED = 2,
		OBJECT_DETECTOR_EVENT_MOVED = 3
	};

	enum class VIDEO_STREAM_MODE
	{
		VIDEO_STREAM_MODE_NONE = 0,
		VIDEO_STREAM_MODE_SOURCE = 1,
		VIDEO_STREAM_MODE_DETECTOR = 2
	};

	enum class VIDEO_STREAM_ENGINE
	{
		VIDEO_STREAM_ENGINE_NONE = 0,
		VIDEO_STREAM_ENGINE_HTTP_MJPG = 1,
		VIDEO_STREAM_ENGINE_SIMPLE_GSTREAMER = 3,
		VIDEO_STREAM_ENGINE_LIVE555 = 4
	};

	enum class INPUT_OUTPUT_DEVICE_KIND
	{
		INPUT_OUTPUT_DEVICE_KIND_NONE= 0,
		INPUT_OUTPUT_DEVICE_KIND_CAMERA = 1,
		INPUT_OUTPUT_DEVICE_KIND_MICROPHONE = 2,
		INPUT_OUTPUT_DEVICE_KIND_SPEAKER = 3,
		INPUT_OUTPUT_DEVICE_KIND_EARPHONES = 4,
		INPUT_OUTPUT_DEVICE_KIND_SENSOR = 5,
		INPUT_OUTPUT_DEVICE_KIND_VIDEO_STREAMER = 6,
		INPUT_OUTPUT_DEVICE_KIND_MQTT_REQUEST = 7
	};

	enum class ILLUSTRATION_STYLE
	{
		ILLUSTRATION_STYLE_NONE = 0,
		ILLUSTRATION_STYLE_BOX = 1,
		ILLUSTRATION_STYLE_BOX_AND_TEXT = 2,
		ILLUSTRATION_STYLE_MASK = 3,
		ILLUSTRATION_STYLE_MASK_AND_TEXT = 4
	};

#ifdef __WITH_SCRIPT_LANG__
	enum class SCRIPT_EXECUTE_MODE
	{
		SCRIPT_EXECUTE_MODE_NONE = 0,
		SCRIPT_EXECUTE_MODE_SYNC = 1,
		SCRIPT_EXECUTE_MODE_ASYNC = 2
	};
#endif
}
